<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">
<span style="color:purple;font-size:13pt"><b>Data Dictionary</span></b>
</div>

<div style="width:900px;float:left;padding:20px;align:left;">
Descriptors:
<br><br>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-2lp6{font-weight:bold;background-color:#bbdaff;vertical-align:top}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-36xf{font-weight:bold;background-color:#bbdaff}
.tg .tg-yw4l{vertical-align:top}
.tg .tg-yw42{vertical-align:top;color:blue}
</style>
<table class="tg">

  <tr>
    <th class="tg-36xf">Feature Name</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
  </tr>
          
<tr>
    <td class="tg-yw4l">RecordID</td>
    <td class="tg-yw4l">A unique integer for each ICU stay </td>
    <td class="tg-yw4l">Integer</td>
</tr>
<tr>
    <td class="tg-yw4l">Age</td>
    <td class="tg-yw4l">Age</td>
    <td class="tg-yw4l">(years)</td>
</tr>

<tr>
    <td class="tg-yw4l">Height</td>
    <td class="tg-yw4l">Height</td>
    <td class="tg-yw4l">(cm)</td>
</tr>

<tr>
    <td class="tg-yw4l">ICUtype</td>
    <td class="tg-yw4l">ICU Type</td>
    <td class="tg-yw4l">(1: Coronary Care Unit, 2: Cardiac Surgery Recovery Unit, <br>3: Medical ICU, or 4: Surgical ICU)</td>
</tr>

<tr>
    <td class="tg-yw4l">Gender</td>
    <td class="tg-yw4l">Gender</td>
    <td class="tg-yw4l">(0: female, or 1: male)</td>
</tr>

</table>
<br><br>
These 37 variables may be observed once, more than once, or not at all in some cases:
<br><br>

<table class="tg">
<tr>
    <th class="tg-36xf">Feature Name</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
</tr>
          
<tr>
    <td class="tg-yw4l">Albumin</td>
    <td class="tg-yw4l">Albumin </td>
    <td class="tg-yw4l">(g/dL)</td>
</tr>
<tr>
    <td class="tg-yw4l">ALP</td>
    <td class="tg-yw4l">Alkaline phosphatase</td>
    <td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">ALT</td>
<td class="tg-yw4l">Alanine transaminase</td> 
<td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">AST</td>
<td class="tg-yw4l">Aspartate transaminase</td>
<td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">Bilirubin</td>
<td class="tg-yw4l">Bilirubin</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">BUN</td>
<td class="tg-yw4l">Blood urea nitrogen</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">Cholesterol</td>
<td class="tg-yw4l">Cholesterol</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">Creatinine</td>
<td class="tg-yw4l">Serum creatinine</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>

<tr>
<td class="tg-yw4l">DiasABP <td class="tg-yw4l">Invasive diastolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>

<tr><td class="tg-yw4l">FiO2 <td class="tg-yw4l">Fractional inspired O2 <td class="tg-yw4l">(0-1)</tr>
<tr><td class="tg-yw4l">GCS <td class="tg-yw4l">Glasgow Coma Score <td class="tg-yw4l">(3-15)</tr>
<tr><td class="tg-yw4l">Glucose <td class="tg-yw4l">Serum glucose <td class="tg-yw4l">(mg/dL)</tr>
<tr><td class="tg-yw4l">HCO3 <td class="tg-yw4l">Serum bicarbonate <td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">HCT <td class="tg-yw4l">Hematocrit <td class="tg-yw4l">(%)</tr>
<tr><td class="tg-yw4l">HR <td class="tg-yw4l">Heart rate <td class="tg-yw4l">(bpm)</tr>
<tr><td class="tg-yw4l">K <td class="tg-yw4l">Serum potassium <td class="tg-yw4l">(mEq/L)</tr>
<tr><td class="tg-yw4l">Lactate <td class="tg-yw4l">Lactate<td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">Mg <td class="tg-yw4l">Serum magnesium <td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">MAP <td class="tg-yw4l">Invasive mean arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">MechVent <td class="tg-yw4l">Mechanical ventilation respiration <td class="tg-yw4l">(0:false, or 1:true)</tr>
<tr><td class="tg-yw4l">Na <td class="tg-yw4l">Serum sodium <td class="tg-yw4l">(mEq/L)</tr>
<tr><td class="tg-yw4l">NIDiasABP <td class="tg-yw4l">Non-invasive diastolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">NIMAP <td class="tg-yw4l">Non-invasive mean arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">NISysABP <td class="tg-yw4l">Non-invasive systolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">PaCO2 <td class="tg-yw4l">partial pressure of arterial CO2 <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">PaO2 <td class="tg-yw4l">Partial pressure of arterial O2 <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">pH <td class="tg-yw4l">Arterial pH <td class="tg-yw4l">(0-14)</tr>
<tr><td class="tg-yw4l">Platelets <td class="tg-yw4l">Platelets<td class="tg-yw4l">(cells/nL)</tr>
<tr><td class="tg-yw4l">RespRate <td class="tg-yw4l">Respiration rate <td class="tg-yw4l">(bpm)</tr>
<tr><td class="tg-yw4l">SaO2 <td class="tg-yw4l">O2 saturation in hemoglobin <td class="tg-yw4l">(%)</tr>
<tr><td class="tg-yw4l">SysABP <td class="tg-yw4l">Invasive systolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">Temp <td class="tg-yw4l">Temperature <td class="tg-yw4l">(°C)</tr>
<tr><td class="tg-yw4l">TropI <td class="tg-yw4l">Troponin-I <td class="tg-yw4l">(μg/L)</tr>
<tr><td class="tg-yw4l">TropT <td class="tg-yw4l">Troponin-T <td class="tg-yw4l">(μg/L)</tr>
<tr><td class="tg-yw4l">Urine <td class="tg-yw4l">Urine output <td class="tg-yw4l">(mL)</tr>
<tr><td class="tg-yw4l">WBC <td class="tg-yw4l">White blood cell count <td class="tg-yw4l">(cells/nL)</tr>
<tr><td class="tg-yw4l">Weight <td class="tg-yw4l">Weight<td class="tg-yw4l">(kg)</tr></table>

<br><br>
Outcomes-Related Descriptors:

<table class="tg">
<tr>
    <th class="tg-36xf">Outcomes</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
</tr>
          
<tr>
    <td class="tg-yw4l">SAPS-I score</td>
    <td class="tg-yw4l">(Le Gall et al., 1984) </td>
    <td class="tg-yw4l">between 0 to 163</td>
</tr>
  
<tr>
    <td class="tg-yw4l">SOFA score</td>
    <td class="tg-yw4l">(Ferreira et al., 2001) </td>
    <td class="tg-yw4l">between 0 to 4</td>
</tr>
  
<tr>
    <td class="tg-yw4l">Length of stay</td>
    <td class="tg-yw4l">Length of stay </td>
    <td class="tg-yw4l">(days)</td>
</tr>

<tr>
    <td class="tg-yw4l">Survival</td>
    <td class="tg-yw4l">Survival</td>
    <td class="tg-yw4l">(days)</td>
</tr>

<tr>
    <td class="tg-yw42"><b>In-hospital death</b></td>
    <td class="tg-yw42"><b>Target Variable</b></td>
    <td class="tg-yw42"><b>(0: survivor, or 1: died in-hospital)</b></td>
</tr>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<span style="color:purple;font-size:13pt"><b>Import Packages</span></b>

</div>

In [1]:
# Import packages

import glob
import csv
import pandas as pd
import numpy as np

from sqlalchemy import create_engine
import psycopg2

import re

import seaborn as sns

from sklearn import preprocessing

from fancyimpute import SoftImpute

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows',200)


sns.set_style('whitegrid')
sns.set(rc={"figure.figsize": (15, 8)})

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<span style="color:purple;font-size:13pt"><b>Check if data is unbalanced</span></b>

</div>

In [2]:
# Open set a outcomes file as dataframe
with open('training_outcomes_a.txt') as outcomesfile:
        
        label = list(csv.reader(outcomesfile))                      # list of list
        label = pd.DataFrame(label[1:],columns=label[0])            # Convert list of list to DataFrame
        
        label = label.astype(float)                                 # Change all values to float
        label.columns = label.columns.str.lower()                   # Change all column to lowercase
        
        
        label.set_index(['recordid'],inplace = True)                # set recordid as index

In [3]:
# Count the number of positives in dataset
# Positives = 1 = Death, Negative = 0 = Survived

def imbalance_check(column,labels):
    """labels can be a list or a tuple."""
    
    for x in labels:
        label = float(column[column == x].count())
        total = float(column.count())
        
        percentage = float((label/total)*100)
        
        print 'percentage of',x,'in dataset:',percentage,'%'

In [4]:
imbalance_check(label['in-hospital_death'],[0,1])     # This is an imbalanced dataset

percentage of 0 in dataset: 86.15 %
percentage of 1 in dataset: 13.85 %

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">



<p>
<span style="color:purple;font-size:13pt"><b>Read Data</span></b>
<br>
<br><b>Step 1:</b> Iterate through each patient record file
<br><br>
<span style="color:purple;font-size:13pt"><b>Feature Engineering</span></b>
<br><br>
<b>Step 2:</b> Pivot-table and aggregate time series using: <b>Mean, Min, Max, First (data obtained), Last (data obtained)</b>
<br><br>
<span style="color:purple;font-size:13pt"><b>Data Cleaning</span></b>
<br><br>
<b>Step 3:</b> Replace -1 values to Nan
<br><br><i> According to data description, all valid values for general descriptors, time series variables, and outcome-related descriptors are non-negative (≥ 0). A value of -1 indicates missing or unknown data (for example, if a patient's height was not recorded).</i>
<br><br>
<span style="color:purple;font-size:13pt"><b>Construct main DataFrame with all data</span></b>
<br><br>
<b>Step 4:</b> Append each patient record file into a main dataframe
</div>

In [5]:
# Function to obtain the first data within 48 hours

def first_data(column):

    x = column.iloc[0]
    
    return x


# Function to obtain the last data within 48 hours

def last_data(column):
    
    x = column.iloc[-1]

    return x

In [6]:
# Iterate through each file name

main = pd.DataFrame()

for filename in glob.iglob('./training_set_a/*.txt'):
    
    # Open each file as data
    with open(filename) as inputfile:
        
        data = list(csv.reader(inputfile))                      # list of list
        data = pd.DataFrame(data[1:],columns=data[0])           # Convert list of list to DataFrame
        data.Value = data.Value.astype(float)                   # Change Value to float
        
        
        
        # Pivot_table to convert from long to wide dataset

        # Creation of new features - aggregate across the time series to find mean, min, max values
        # mean is chosen rather than median because we want to take into the account of 'outlier values'

        wide_data = pd.pivot_table(data,values=['Value'],columns='Parameter',aggfunc=[np.mean,np.min,np.max,
                                                                                      first_data,last_data])
        wide_data.columns = wide_data.columns.droplevel(level=0)
        
        
        
        # rename new columns & lower capitalise
        new_columns = []

        for ind, col in enumerate(wide_data.columns):
    
            if ind < wide_data.columns.shape[0]/5:
                col = 'mean_'+col            
                new_columns.append(col)

            elif ind >= wide_data.columns.shape[0]/5 and ind < 2*(wide_data.columns.shape[0]/5):
                col = 'min_'+col
                new_columns.append(col)
        
            elif ind >= 2*(wide_data.columns.shape[0]/5) and ind < 3*(wide_data.columns.shape[0]/5):
                col = 'max_'+col
                new_columns.append(col)
        
            elif ind >= 3*(wide_data.columns.shape[0]/5) and ind < 4*(wide_data.columns.shape[0]/5):
                col = 'first_'+col
                new_columns.append(col)

            else:
                col = 'last_'+col
                new_columns.append(col)
        
        wide_data.columns = new_columns
        wide_data.columns = wide_data.columns.str.lower()
        
        
        # rename descriptor row
        wide_data.rename(columns={'mean_age':'age','mean_gender':'gender','mean_height':'height',
                                    'mean_icutype':'icutype','mean_recordid':'recordid'},inplace=True)
        
        
        # drop min/max/first/last descriptor rows
        drop_col = wide_data.columns[wide_data.columns.str.contains(
            '\w+_age|\w+_height|\w+_gender|\w+_icutype|\w+_recordid')]
        
        wide_data.drop(drop_col,axis=1,inplace=True)
        
        # set recordid as index
        wide_data.set_index(['recordid'],inplace = True)
        
        # replace -1 as NaN
        wide_data.replace(-1,np.nan,inplace=True)
        
        main = main.append(wide_data)
        
# merge main data and label data
mortality = main.merge(label,how='outer',left_index=True,right_index=True)

In [7]:
mortality.isnull().sum()

age                     0
first_albumin        2385
first_alp            2310
first_alt            2279
first_ast            2275
first_bilirubin      2282
first_bun              64
first_cholesterol    3695
first_creatinine       64
first_diasabp        1201
first_fio2           1283
first_gcs              64
first_glucose         113
first_hco3             76
first_hct              64
first_hr               63
first_k                96
first_lactate        1817
first_map            1208
first_mechvent       1471
first_mg              103
first_na               75
first_nidiasabp       517
first_nimap           519
first_nisysabp        507
first_paco2           977
first_pao2            977
first_ph              960
first_platelets        68
first_resprate       2899
first_sao2           2208
first_sysabp         1201
first_temp             64
first_troponini      3795
first_troponint      3137
first_urine           117
first_wbc              73
first_weight          326
gender                  3
height               1894
icutype                 0
last_albumin         2385
last_alp             2310
last_alt             2279
last_ast             2275
last_bilirubin       2282
last_bun               64
last_cholesterol     3695
last_creatinine        64
last_diasabp         1201
last_fio2            1283
last_gcs               64
last_glucose          113
last_hco3              76
last_hct               64
last_hr                63
last_k                 96
last_lactate         1817
last_map             1208
last_mechvent        1471
last_mg               103
last_na                75
last_nidiasabp        517
last_nimap            519
last_nisysabp         507
last_paco2            977
last_pao2             977
last_ph               960
last_platelets         68
last_resprate        2899
last_sao2            2208
last_sysabp          1201
last_temp              64
last_troponini       3795
last_troponint       3137
last_urine            117
last_wbc               73
last_weight           296
max_albumin          2385
max_alp              2310
max_alt              2279
max_ast              2275
max_bilirubin        2282
max_bun                64
max_cholesterol      3695
max_creatinine         64
max_diasabp          1201
max_fio2             1283
max_gcs                64
max_glucose           113
max_hco3               76
max_hct                64
max_hr                 63
max_k                  96
max_lactate          1817
max_map              1208
max_mechvent         1471
max_mg                103
max_na                 75
max_nidiasabp         517
max_nimap             519
max_nisysabp          507
max_paco2             977
max_pao2              977
max_ph                960
max_platelets          68
max_resprate         2899
max_sao2             2208
max_sysabp           1201
max_temp               64
max_troponini        3795
max_troponint        3137
max_urine             117
max_wbc                73
max_weight            296
mean_albumin         2385
mean_alp             2310
mean_alt             2279
mean_ast             2275
mean_bilirubin       2282
mean_bun               64
mean_cholesterol     3695
mean_creatinine        64
mean_diasabp         1201
mean_fio2            1283
mean_gcs               64
mean_glucose          113
mean_hco3              76
mean_hct               64
mean_hr                63
mean_k                 96
mean_lactate         1817
mean_map             1208
mean_mechvent        1471
mean_mg               103
mean_na                75
mean_nidiasabp        517
mean_nimap            519
mean_nisysabp         507
mean_paco2            977
mean_pao2             977
mean_ph               960
mean_platelets         68
mean_resprate        2899
mean_sao2            2208
mean_sysabp          1201
mean_temp              64
mean_troponini       3795
mean_troponint       3137
mean_urine            117
mean_wbc               73
mean_weight           296
min_albumin          2385
min_alp              2310
min_alt              2279
min_ast              2275
min_bilirubin        2282
min_bun                64
min_cholesterol      3695
min_creatinine         64
min_diasabp          1201
min_fio2             1283
min_gcs                64
min_glucose           113
min_hco3               76
min_hct                64
min_hr                 63
min_k                  96
min_lactate          1817
min_map              1208
min_mechvent         1471
min_mg                103
min_na                 75
min_nidiasabp         517
min_nimap             519
min_nisysabp          507
min_paco2             977
min_pao2              977
min_ph                960
min_platelets          68
min_resprate         2899
min_sao2             2208
min_sysabp           1201
min_temp               64
min_troponini        3795
min_troponint        3137
min_urine             117
min_wbc                73
min_weight            326
saps-i                  0
sofa                    0
length_of_stay          0
survival                0
in-hospital_death       0
dtype: int64

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Data Cleaning</span></b>
<br><br>
<b>Step 1:</b> Drop all columns with more than 75% NaN values
<br><b>Step 2:</b> Drop all rows with more than 50% NaN values
<br><b>Step 3:</b> Drop all other outcomes labels except 'in-hospital_death'
</div>

In [8]:
# NaN values count (columns)

null_col = mortality.isnull().sum()
null_col[null_col > 1000].index  # columns that contain more than 3/4 NaN values (75% of the rows)

mortality.drop(null_col[null_col > 1000].index,axis=1,inplace = True)

In [9]:
# NaN values count (rows)

mortality['NaNs'] = mortality.isnull().sum(axis=1)
mortality[mortality['NaNs']>57].index  # rows that contain more than 57 NaN values (50% of the features)

mortality.drop(mortality[mortality['NaNs']>57].index,inplace=True)

In [10]:
# Drop other labels

label_others = mortality.drop(['saps-i','sofa','length_of_stay','survival'],axis=1)
mortality.drop(['saps-i','sofa','length_of_stay','survival'],axis=1,inplace=True)

In [11]:
# Drop NaN column

mortality.drop(['NaNs'],axis=1,inplace=True)

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Imputing Missing Data</span></b>
<br><br>
<b>1:</b> Impute values based on median of gender, age & icutype
<br><b>2:</b> Impute values based on KNN
</div>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Feature Selection</span></b>
<br><br>
Variance Inflation Factor (multi-colinearity)
<br>
Near Zero Variance
<br>
Decision Trees/Random Forest on Feature Importance
<br>
Filter: Linear Discriminant Analysis
<br>
Pearson Correlation to check for multi-colinearity
<br>
Wrapper: LassoCV
<br>
Wrapper: RFE on Logistic Regression
</div>