<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">
<span style="color:purple;font-size:13pt"><b>Data Dictionary</span></b>
</div>

<div style="width:900px;float:left;padding:20px;align:left;">
Descriptors:
<br><br>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-2lp6{font-weight:bold;background-color:#bbdaff;vertical-align:top}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-36xf{font-weight:bold;background-color:#bbdaff}
.tg .tg-yw4l{vertical-align:top}
.tg .tg-yw42{vertical-align:top;color:blue}
</style>
<table class="tg">

  <tr>
    <th class="tg-36xf">Feature Name</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
  </tr>
          
<tr>
    <td class="tg-yw4l">RecordID</td>
    <td class="tg-yw4l">A unique integer for each ICU stay </td>
    <td class="tg-yw4l">Integer</td>
</tr>
<tr>
    <td class="tg-yw4l">Age</td>
    <td class="tg-yw4l">Age</td>
    <td class="tg-yw4l">(years)</td>
</tr>

<tr>
    <td class="tg-yw4l">Height</td>
    <td class="tg-yw4l">Height</td>
    <td class="tg-yw4l">(cm)</td>
</tr>

<tr>
    <td class="tg-yw4l">ICUtype</td>
    <td class="tg-yw4l">ICU Type</td>
    <td class="tg-yw4l">(1: Coronary Care Unit, 2: Cardiac Surgery Recovery Unit, <br>3: Medical ICU, or 4: Surgical ICU)</td>
</tr>

<tr>
    <td class="tg-yw4l">Gender</td>
    <td class="tg-yw4l">Gender</td>
    <td class="tg-yw4l">(0: female, or 1: male)</td>
</tr>

</table>
<br><br>
These 37 variables may be observed once, more than once, or not at all in some cases:
<br><br>

<table class="tg">
<tr>
    <th class="tg-36xf">Feature Name</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
</tr>
          
<tr>
    <td class="tg-yw4l">Albumin</td>
    <td class="tg-yw4l">Albumin </td>
    <td class="tg-yw4l">(g/dL)</td>
</tr>
<tr>
    <td class="tg-yw4l">ALP</td>
    <td class="tg-yw4l">Alkaline phosphatase</td>
    <td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">ALT</td>
<td class="tg-yw4l">Alanine transaminase</td> 
<td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">AST</td>
<td class="tg-yw4l">Aspartate transaminase</td>
<td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">Bilirubin</td>
<td class="tg-yw4l">Bilirubin</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">BUN</td>
<td class="tg-yw4l">Blood urea nitrogen</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">Cholesterol</td>
<td class="tg-yw4l">Cholesterol</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">Creatinine</td>
<td class="tg-yw4l">Serum creatinine</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>

<tr>
<td class="tg-yw4l">DiasABP <td class="tg-yw4l">Invasive diastolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>

<tr><td class="tg-yw4l">FiO2 <td class="tg-yw4l">Fractional inspired O2 <td class="tg-yw4l">(0-1)</tr>
<tr><td class="tg-yw4l">GCS <td class="tg-yw4l">Glasgow Coma Score <td class="tg-yw4l">(3-15)</tr>
<tr><td class="tg-yw4l">Glucose <td class="tg-yw4l">Serum glucose <td class="tg-yw4l">(mg/dL)</tr>
<tr><td class="tg-yw4l">HCO3 <td class="tg-yw4l">Serum bicarbonate <td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">HCT <td class="tg-yw4l">Hematocrit <td class="tg-yw4l">(%)</tr>
<tr><td class="tg-yw4l">HR <td class="tg-yw4l">Heart rate <td class="tg-yw4l">(bpm)</tr>
<tr><td class="tg-yw4l">K <td class="tg-yw4l">Serum potassium <td class="tg-yw4l">(mEq/L)</tr>
<tr><td class="tg-yw4l">Lactate <td class="tg-yw4l">Lactate<td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">Mg <td class="tg-yw4l">Serum magnesium <td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">MAP <td class="tg-yw4l">Invasive mean arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">MechVent <td class="tg-yw4l">Mechanical ventilation respiration <td class="tg-yw4l">(0:false, or 1:true)</tr>
<tr><td class="tg-yw4l">Na <td class="tg-yw4l">Serum sodium <td class="tg-yw4l">(mEq/L)</tr>
<tr><td class="tg-yw4l">NIDiasABP <td class="tg-yw4l">Non-invasive diastolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">NIMAP <td class="tg-yw4l">Non-invasive mean arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">NISysABP <td class="tg-yw4l">Non-invasive systolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">PaCO2 <td class="tg-yw4l">partial pressure of arterial CO2 <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">PaO2 <td class="tg-yw4l">Partial pressure of arterial O2 <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">pH <td class="tg-yw4l">Arterial pH <td class="tg-yw4l">(0-14)</tr>
<tr><td class="tg-yw4l">Platelets <td class="tg-yw4l">Platelets<td class="tg-yw4l">(cells/nL)</tr>
<tr><td class="tg-yw4l">RespRate <td class="tg-yw4l">Respiration rate <td class="tg-yw4l">(bpm)</tr>
<tr><td class="tg-yw4l">SaO2 <td class="tg-yw4l">O2 saturation in hemoglobin <td class="tg-yw4l">(%)</tr>
<tr><td class="tg-yw4l">SysABP <td class="tg-yw4l">Invasive systolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">Temp <td class="tg-yw4l">Temperature <td class="tg-yw4l">(°C)</tr>
<tr><td class="tg-yw4l">TropI <td class="tg-yw4l">Troponin-I <td class="tg-yw4l">(μg/L)</tr>
<tr><td class="tg-yw4l">TropT <td class="tg-yw4l">Troponin-T <td class="tg-yw4l">(μg/L)</tr>
<tr><td class="tg-yw4l">Urine <td class="tg-yw4l">Urine output <td class="tg-yw4l">(mL)</tr>
<tr><td class="tg-yw4l">WBC <td class="tg-yw4l">White blood cell count <td class="tg-yw4l">(cells/nL)</tr>
<tr><td class="tg-yw4l">Weight <td class="tg-yw4l">Weight<td class="tg-yw4l">(kg)</tr></table>

<br><br>
Outcomes-Related Descriptors:

<table class="tg">
<tr>
    <th class="tg-36xf">Outcomes</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
</tr>
          
<tr>
    <td class="tg-yw4l">SAPS-I score</td>
    <td class="tg-yw4l">(Le Gall et al., 1984) </td>
    <td class="tg-yw4l">between 0 to 163</td>
</tr>
  
<tr>
    <td class="tg-yw4l">SOFA score</td>
    <td class="tg-yw4l">(Ferreira et al., 2001) </td>
    <td class="tg-yw4l">between 0 to 4</td>
</tr>
  
<tr>
    <td class="tg-yw4l">Length of stay</td>
    <td class="tg-yw4l">Length of stay </td>
    <td class="tg-yw4l">(days)</td>
</tr>

<tr>
    <td class="tg-yw4l">Survival</td>
    <td class="tg-yw4l">Survival</td>
    <td class="tg-yw4l">(days)</td>
</tr>

<tr>
    <td class="tg-yw42"><b>In-hospital death</b></td>
    <td class="tg-yw42"><b>Target Variable</b></td>
    <td class="tg-yw42"><b>(0: survivor, or 1: died in-hospital)</b></td>
</tr>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<span style="color:purple;font-size:13pt"><b>Import Packages</span></b>

</div>

In [1]:
# Import packages

import glob
import csv
import pandas as pd
import numpy as np

from sqlalchemy import create_engine
import psycopg2

import re

import seaborn as sns

from sklearn.preprocessing import scale

from fancyimpute import SoftImpute, KNN

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows',200)


sns.set_style('whitegrid')
sns.set(rc={"figure.figsize": (15, 8)})

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [2]:
mortality = pd.read_csv('mortality.csv')

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Data Cleaning</span></b>
<br><br>
<b>Step 1:</b> Drop all columns with more than 25% NaN values
<br><b>Step 2:</b> Drop all rows with more than 50% NaN values
<br><b>Step 3:</b> Drop all other outcomes labels except 'in-hospital_death'
</div>

In [3]:
# NaN values count (columns)

null_col = mortality.isnull().sum()
null_col[null_col > 1000].index  # columns that contain more than 3/4 NaN values (75% of the rows)

mortality.drop(null_col[null_col > 1000].index,axis=1,inplace = True)

In [4]:
# NaN values count (rows)

mortality['NaNs'] = mortality.isnull().sum(axis=1)
mortality[mortality['NaNs']>57].index  # rows that contain more than 57 NaN values (50% of the features)

mortality.drop(mortality[mortality['NaNs']>57].index,inplace=True)

In [5]:
# Drop other labels

label_others = mortality.drop(['saps-i','sofa','length_of_stay','survival'],axis=1)
mortality.drop(['saps-i','sofa','length_of_stay','survival'],axis=1,inplace=True)

In [6]:
# Drop NaN column

mortality.drop(['NaNs'],axis=1,inplace=True)

In [ ]:
class DropNaN(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        pass
    
    def remove_columns_(self,df,drop_col):
        """remove columns with more than 1000 NaN values"""
        
        drop_col = 1000
        null_col = df.isnull().sum()
        df = df.drop(null_col[null_col > drop_col].index,axis=1)
        
        return df
    
    def remove_rows_(self,df,drop_row):
        
        drop_row = 57
        df['NaNs'] = mortality.isnull().sum(axis=1)
        df = df.drop(df[df['NaNs']>drop_row].index)
        
        return df
    
    def drop_deslabels_(self,df,deslabels):
        
        deslabels = ['saps-i','sofa','length_of_stay','survival']
        df = df.drop(deslabels,axis=1)
        
        return df
    
    def transform(self, main_df, *args):
        
        main_df = self.remove_columns_(main_df)
        main_df = self.remove_rows_(main_df)
        main_df = self.drop_deslabels_(main_df)
        
        self.feature_names = X.columns
        
        return X

    def fit(self, X, *args):
        return self

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Imputing Missing Data</span></b>
<br><br><b>2:</b> Impute values based on KNN
</div>

In [7]:
mortality.isnull().sum()

recordid               0
age                    0
first_bun             30
first_creatinine      30
first_gcs             58
first_glucose         79
first_hco3            42
first_hct             31
first_hr              58
first_k               62
first_mg              69
first_na              41
first_nidiasabp      507
first_nimap          509
first_nisysabp       497
first_paco2          946
first_pao2           946
first_ph             929
first_platelets       33
first_temp            58
first_urine          111
first_wbc             38
first_weight         314
gender                 3
icutype                0
last_bun              30
last_creatinine       30
last_gcs              58
last_glucose          79
last_hco3             42
last_hct              31
last_hr               58
last_k                62
last_mg               69
last_na               41
last_nidiasabp       507
last_nimap           509
last_nisysabp        497
last_paco2           946
last_pao2            946
last_ph              929
last_platelets        33
last_temp             58
last_urine           111
last_wbc              38
last_weight          286
max_bun               30
max_creatinine        30
max_gcs               58
max_glucose           79
max_hco3              42
max_hct               31
max_hr                58
max_k                 62
max_mg                69
max_na                41
max_nidiasabp        507
max_nimap            509
max_nisysabp         497
max_paco2            946
max_pao2             946
max_ph               929
max_platelets         33
max_temp              58
max_urine            111
max_wbc               38
max_weight           286
mean_bun              30
mean_creatinine       30
mean_gcs              58
mean_glucose          79
mean_hco3             42
mean_hct              31
mean_hr               58
mean_k                62
mean_mg               69
mean_na               41
mean_nidiasabp       507
mean_nimap           509
mean_nisysabp        497
mean_paco2           946
mean_pao2            946
mean_ph              929
mean_platelets        33
mean_temp             58
mean_urine           111
mean_wbc              38
mean_weight          286
min_bun               30
min_creatinine        30
min_gcs               58
min_glucose           79
min_hco3              42
min_hct               31
min_hr                58
min_k                 62
min_mg                69
min_na                41
min_nidiasabp        507
min_nimap            509
min_nisysabp         497
min_paco2            946
min_pao2             946
min_ph               929
min_platelets         33
min_temp              58
min_urine            111
min_wbc               38
min_weight           314
in-hospital_death      0
dtype: int64

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Finding the best K</span></b>
<br><br>
(for each column)
<br><br>
<b>Step 1:</b> Extract rows with no missing values for a particular column (train set)
<br>
<b>Step 2:</b> Do a CV on on train set find optimal K
<br>
<b>Step 3:</b> Use optimal K on KNN fancyimpute
</div>

In [12]:
# Obtain one subset

subset_col = mortality.columns[mortality.columns.str.contains('mean_\w+')]
subset_mortality = mortality[subset_col]

In [13]:
subset_mortality.isnull().sum()

mean_bun            30
mean_creatinine     30
mean_gcs            58
mean_glucose        79
mean_hco3           42
mean_hct            31
mean_hr             58
mean_k              62
mean_mg             69
mean_na             41
mean_nidiasabp     507
mean_nimap         509
mean_nisysabp      497
mean_paco2         946
mean_pao2          946
mean_ph            929
mean_platelets      33
mean_temp           58
mean_urine         111
mean_wbc            38
mean_weight        286
dtype: int64

In [51]:
# Loop through each column

def find_best_k_cls(X, y, k_min=1, k_max=51, step=1, cv=5):
    
    k_range = range(k_min, k_max+1, step)
    accs = []
    
    for k in k_range:
        
        knn = KNeighborsRegressor(n_neighbors=k,weights='distance')
        scores = cross_val_score(knn, X, y, cv=cv)
        accs.append(np.mean(scores))

        
    print 'accuracy:',np.max(accs),'best k:',k_range[np.argmax(accs)]
    return (np.max(accs),k_range[np.argmax(accs)])

best_ks = []
feature_list = []

for feature in subset_mortality.columns:
    
    impute_missing = subset_mortality.loc[subset_mortality[feature].isnull(), :]  # test
    impute_valid = subset_mortality.loc[~subset_mortality[feature].isnull(), :]   # train
    
    y = impute_valid[feature].values
    X = impute_valid.drop([feature],axis=1)
    
    # Standard Scale 

    scaled_array = []

    for col in X.columns:

        masked_X = np.ma.array(X[col], mask=np.isnan(X[col]))

        masked_mean = np.mean(masked_X)
        masked_std = np.std(masked_X)

        scaled_col = np.array((masked_X - masked_mean)/masked_std)

        scaled_array.append(scaled_col)

    np.transpose(scaled_array)
    Xn = pd.DataFrame(data=np.transpose(scaled_array),columns=X.columns,index=X.index)
    
    Xn.fillna(Xn.mean(),inplace=True)
    
    feature_list.append(feature)
    best_ks.append(find_best_k_cls(Xn,y))
    
    print feature,find_best_k_cls(Xn,y)

accuracy: 0.457916808193 best k: 8
mean_bun accuracy: 0.457916808193 best k: 8
(0.45791680819271596, 8)
accuracy: 0.427825948718 best k: 8
mean_creatinine accuracy: 0.427825948718 best k: 8
(0.42782594871808322, 8)
accuracy: 0.203645564615 best k: 20
mean_gcs accuracy: 0.203645564615 best k: 20
(0.20364556461510813, 20)
accuracy: 0.0288583942041 best k: 46
mean_glucose accuracy: 0.0288583942041 best k: 46
(0.028858394204136585, 46)
accuracy: 0.350347928361 best k: 18
mean_hco3 accuracy: 0.350347928361 best k: 18
(0.35034792836107587, 18)
accuracy: 0.16623157253 best k: 41
mean_hct accuracy: 0.16623157253 best k: 41
(0.16623157253026999, 41)
accuracy: 0.136066885231 best k: 35
mean_hr accuracy: 0.136066885231 best k: 35
(0.13606688523051452, 35)
accuracy: 0.226601404218 best k: 35
mean_k accuracy: 0.226601404218 best k: 35
(0.22660140421766664, 35)
accuracy: 0.120951935352 best k: 46
mean_mg accuracy: 0.120951935352 best k: 46
(0.12095193535204911, 46)
accuracy: 0.0837829317291 best k: 31
mean_na accuracy: 0.0837829317291 best k: 31
(0.083782931729132357, 31)
accuracy: 0.614678707945 best k: 13
mean_nidiasabp accuracy: 0.614678707945 best k: 13
(0.61467870794452073, 13)
accuracy: 0.799074417988 best k: 10
mean_nimap accuracy: 0.799074417988 best k: 10
(0.79907441798788836, 10)
accuracy: 0.479485922519 best k: 17
mean_nisysabp accuracy: 0.479485922519 best k: 17
(0.4794859225187606, 17)
accuracy: 0.40163544286 best k: 9
mean_paco2 accuracy: 0.40163544286 best k: 9
(0.40163544285950853, 9)
accuracy: 0.111286021619 best k: 24
mean_pao2 accuracy: 0.111286021619 best k: 24
(0.11128602161854842, 24)
accuracy: -24.9207078922 best k: 51
mean_ph accuracy: -24.9207078922 best k: 51
(-24.920707892175791, 51)
accuracy: 0.0912651705636 best k: 49
mean_platelets accuracy: 0.0912651705636 best k: 49
(0.091265170563644221, 49)
accuracy: 0.0956271130096 best k: 49
mean_temp accuracy: 0.0956271130096 best k: 49
(0.095627113009622899, 49)
accuracy: 0.133683543128 best k: 51
mean_urine accuracy: 0.133683543128 best k: 51
(0.13368354312775296, 51)
accuracy: 0.0942643467068 best k: 31
mean_wbc accuracy: 0.0942643467068 best k: 31
(0.094264346706828012, 31)
accuracy: 0.0708490946018 best k: 41
mean_weight accuracy: 0.0708490946018 best k: 41
(0.070849094601784096, 41)

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

From the various k values, I will be taking the mean of the k values with R2 > 0.4
<br>
(The optimal k value that can account for most predictions with at least estimated 40% accuracy)
<br>

</p>
</div>

In [8]:
# Standard Scale 

#mortality_predictors = mortality.drop('in-hospital_death',axis=1)

#masked_mortality_predictors = np.ma.array(mortality_predictors, mask=np.isnan(mortality_predictors))

#masked_mean = np.mean(masked_mortality_predictors)
#masked_std = np.std(masked_mortality_predictors)

#norm_mortality_predictors = (masked_mortality_predictors - masked_mean)/masked_std

#mortality_scaled = pd.DataFrame(data=norm_mortality_predictors,columns=mortality_predictors.columns,index=mortality_predictors.index)

In [9]:
#mortality_scaled.head()

In [10]:
# mortality_filled = KNN(k=10).complete(mortality_scaled)

In [11]:
#mortality_filled = pd.DataFrame(data=mortality_filled,
 #                               columns=mortality_predictors.columns,index=mortality_predictors.index)
#mortality_filled.isnull().sum()