<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">
<span style="color:purple;font-size:13pt"><b>Data Dictionary</span></b>
</div>

<div style="width:900px;float:left;padding:20px;align:left;">
Descriptors:
<br><br>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-2lp6{font-weight:bold;background-color:#bbdaff;vertical-align:top}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-36xf{font-weight:bold;background-color:#bbdaff}
.tg .tg-yw4l{vertical-align:top}
.tg .tg-yw42{vertical-align:top;color:blue}
</style>
<table class="tg">

  <tr>
    <th class="tg-36xf">Feature Name</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
  </tr>
          
<tr>
    <td class="tg-yw4l">RecordID</td>
    <td class="tg-yw4l">A unique integer for each ICU stay </td>
    <td class="tg-yw4l">Integer</td>
</tr>
<tr>
    <td class="tg-yw4l">Age</td>
    <td class="tg-yw4l">Age</td>
    <td class="tg-yw4l">(years)</td>
</tr>

<tr>
    <td class="tg-yw4l">Height</td>
    <td class="tg-yw4l">Height</td>
    <td class="tg-yw4l">(cm)</td>
</tr>

<tr>
    <td class="tg-yw4l">ICUtype</td>
    <td class="tg-yw4l">ICU Type</td>
    <td class="tg-yw4l">(1: Coronary Care Unit, 2: Cardiac Surgery Recovery Unit, <br>3: Medical ICU, or 4: Surgical ICU)</td>
</tr>

<tr>
    <td class="tg-yw4l">Gender</td>
    <td class="tg-yw4l">Gender</td>
    <td class="tg-yw4l">(0: female, or 1: male)</td>
</tr>

</table>
<br><br>
These 37 variables may be observed once, more than once, or not at all in some cases:
<br><br>

<table class="tg">
<tr>
    <th class="tg-36xf">Feature Name</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
</tr>
          
<tr>
    <td class="tg-yw4l">Albumin</td>
    <td class="tg-yw4l">Albumin </td>
    <td class="tg-yw4l">(g/dL)</td>
</tr>
<tr>
    <td class="tg-yw4l">ALP</td>
    <td class="tg-yw4l">Alkaline phosphatase</td>
    <td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">ALT</td>
<td class="tg-yw4l">Alanine transaminase</td> 
<td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">AST</td>
<td class="tg-yw4l">Aspartate transaminase</td>
<td class="tg-yw4l">(IU/L)</td>
</tr>
<tr>
<td class="tg-yw4l">Bilirubin</td>
<td class="tg-yw4l">Bilirubin</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">BUN</td>
<td class="tg-yw4l">Blood urea nitrogen</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">Cholesterol</td>
<td class="tg-yw4l">Cholesterol</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>
<tr>
<td class="tg-yw4l">Creatinine</td>
<td class="tg-yw4l">Serum creatinine</td>
<td class="tg-yw4l">(mg/dL)</td>
</tr>

<tr>
<td class="tg-yw4l">DiasABP <td class="tg-yw4l">Invasive diastolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>

<tr><td class="tg-yw4l">FiO2 <td class="tg-yw4l">Fractional inspired O2 <td class="tg-yw4l">(0-1)</tr>
<tr><td class="tg-yw4l">GCS <td class="tg-yw4l">Glasgow Coma Score <td class="tg-yw4l">(3-15)</tr>
<tr><td class="tg-yw4l">Glucose <td class="tg-yw4l">Serum glucose <td class="tg-yw4l">(mg/dL)</tr>
<tr><td class="tg-yw4l">HCO3 <td class="tg-yw4l">Serum bicarbonate <td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">HCT <td class="tg-yw4l">Hematocrit <td class="tg-yw4l">(%)</tr>
<tr><td class="tg-yw4l">HR <td class="tg-yw4l">Heart rate <td class="tg-yw4l">(bpm)</tr>
<tr><td class="tg-yw4l">K <td class="tg-yw4l">Serum potassium <td class="tg-yw4l">(mEq/L)</tr>
<tr><td class="tg-yw4l">Lactate <td class="tg-yw4l">Lactate<td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">Mg <td class="tg-yw4l">Serum magnesium <td class="tg-yw4l">(mmol/L)</tr>
<tr><td class="tg-yw4l">MAP <td class="tg-yw4l">Invasive mean arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">MechVent <td class="tg-yw4l">Mechanical ventilation respiration <td class="tg-yw4l">(0:false, or 1:true)</tr>
<tr><td class="tg-yw4l">Na <td class="tg-yw4l">Serum sodium <td class="tg-yw4l">(mEq/L)</tr>
<tr><td class="tg-yw4l">NIDiasABP <td class="tg-yw4l">Non-invasive diastolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">NIMAP <td class="tg-yw4l">Non-invasive mean arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">NISysABP <td class="tg-yw4l">Non-invasive systolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">PaCO2 <td class="tg-yw4l">partial pressure of arterial CO2 <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">PaO2 <td class="tg-yw4l">Partial pressure of arterial O2 <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">pH <td class="tg-yw4l">Arterial pH <td class="tg-yw4l">(0-14)</tr>
<tr><td class="tg-yw4l">Platelets <td class="tg-yw4l">Platelets<td class="tg-yw4l">(cells/nL)</tr>
<tr><td class="tg-yw4l">RespRate <td class="tg-yw4l">Respiration rate <td class="tg-yw4l">(bpm)</tr>
<tr><td class="tg-yw4l">SaO2 <td class="tg-yw4l">O2 saturation in hemoglobin <td class="tg-yw4l">(%)</tr>
<tr><td class="tg-yw4l">SysABP <td class="tg-yw4l">Invasive systolic arterial blood pressure <td class="tg-yw4l">(mmHg)</tr>
<tr><td class="tg-yw4l">Temp <td class="tg-yw4l">Temperature <td class="tg-yw4l">(°C)</tr>
<tr><td class="tg-yw4l">TropI <td class="tg-yw4l">Troponin-I <td class="tg-yw4l">(μg/L)</tr>
<tr><td class="tg-yw4l">TropT <td class="tg-yw4l">Troponin-T <td class="tg-yw4l">(μg/L)</tr>
<tr><td class="tg-yw4l">Urine <td class="tg-yw4l">Urine output <td class="tg-yw4l">(mL)</tr>
<tr><td class="tg-yw4l">WBC <td class="tg-yw4l">White blood cell count <td class="tg-yw4l">(cells/nL)</tr>
<tr><td class="tg-yw4l">Weight <td class="tg-yw4l">Weight<td class="tg-yw4l">(kg)</tr></table>

<br><br>
Outcomes-Related Descriptors:

<table class="tg">
<tr>
    <th class="tg-36xf">Outcomes</th>
    <th class="tg-2lp6">Description</th>
    <th class="tg-2lp6">Metrics</th>
</tr>
          
<tr>
    <td class="tg-yw4l">SAPS-I score</td>
    <td class="tg-yw4l">(Le Gall et al., 1984) </td>
    <td class="tg-yw4l">between 0 to 163</td>
</tr>
  
<tr>
    <td class="tg-yw4l">SOFA score</td>
    <td class="tg-yw4l">(Ferreira et al., 2001) </td>
    <td class="tg-yw4l">between 0 to 4</td>
</tr>
  
<tr>
    <td class="tg-yw4l">Length of stay</td>
    <td class="tg-yw4l">Length of stay </td>
    <td class="tg-yw4l">(days)</td>
</tr>

<tr>
    <td class="tg-yw4l">Survival</td>
    <td class="tg-yw4l">Survival</td>
    <td class="tg-yw4l">(days)</td>
</tr>

<tr>
    <td class="tg-yw42"><b>In-hospital death</b></td>
    <td class="tg-yw42"><b>Target Variable</b></td>
    <td class="tg-yw42"><b>(0: survivor, or 1: died in-hospital)</b></td>
</tr>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<span style="color:purple;font-size:13pt"><b>Import Packages</span></b>

</div>

In [1]:
# Import packages

import glob
import csv
import pandas as pd
import numpy as np

from sqlalchemy import create_engine
import psycopg2

import re

import seaborn as sns

from sklearn import preprocessing

from fancyimpute import SoftImpute

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows',200)


sns.set_style('whitegrid')
sns.set(rc={"figure.figsize": (15, 8)})

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<span style="color:purple;font-size:13pt"><b>Check if data is unbalanced</span></b>

</div>

In [2]:
# Open set a outcomes file as dataframe
with open('training_outcomes_a.txt') as outcomesfile:
        
        label = list(csv.reader(outcomesfile))                      # list of list
        label = pd.DataFrame(label[1:],columns=label[0])            # Convert list of list to DataFrame
        
        label = label.astype(float)                                 # Change all values to float
        label.columns = label.columns.str.lower()                   # Change all column to lowercase
        
        
        label.set_index(['recordid'],inplace = True)                # set recordid as index

In [3]:
# Count the number of positives in dataset
# Positives = 1 = Death, Negative = 0 = Survived

def imbalance_check(column,labels):
    """labels can be a list or a tuple."""
    
    for x in labels:
        label = float(column[column == x].count())
        total = float(column.count())
        
        percentage = float((label/total)*100)
        
        print 'percentage of',x,'in dataset:',percentage,'%'

In [4]:
imbalance_check(label['in-hospital_death'],[0,1])     # This is an imbalanced dataset

percentage of 0 in dataset: 86.15 %
percentage of 1 in dataset: 13.85 %

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">



<p>
<span style="color:purple;font-size:13pt"><b>Read Data</span></b>
<br>
<br><b>Step 1:</b> Iterate through each patient record file
<br><br>
<span style="color:purple;font-size:13pt"><b>Feature Engineering</span></b>
<br><br>
<b>Step 2:</b> Pivot-table and aggregate time series using: <b>Mean, Min, Max, First (data obtained), Last (data obtained)</b>
<br><br>
<span style="color:purple;font-size:13pt"><b>Data Cleaning</span></b>
<br><br>
<b>Step 3:</b> Replace -1 values to Nan
<br><br><i> According to data description, all valid values for general descriptors, time series variables, and outcome-related descriptors are non-negative (≥ 0). A value of -1 indicates missing or unknown data (for example, if a patient's height was not recorded).</i>
<br><br>
<span style="color:purple;font-size:13pt"><b>Construct main DataFrame with all data</span></b>
<br><br>
<b>Step 4:</b> Append each patient record file into a main dataframe
</div>

In [5]:
# Function to obtain the first data within 48 hours

def first_data(column):

    x = column.iloc[0]
    
    return x


# Function to obtain the last data within 48 hours

def last_data(column):
    
    x = column.iloc[-1]

    return x

In [12]:
# Iterate through each file name

main = pd.DataFrame()

for filename in glob.iglob('./training_set_a/*.txt'):
    
    # Open each file as data
    with open(filename) as inputfile:
        
        data = list(csv.reader(inputfile))                      # list of list
        data = pd.DataFrame(data[1:],columns=data[0])           # Convert list of list to DataFrame
        data.Value = data.Value.astype(float)                   # Change Value to float
        
        
        
        # Pivot_table to convert from long to wide dataset

        # Creation of new features - aggregate across the time series to find mean, min, max values
        # mean is chosen rather than median because we want to take into the account of 'outlier values'

        wide_data = pd.pivot_table(data,values=['Value'],columns='Parameter',aggfunc=[np.mean,np.min,np.max,
                                                                                      first_data,np.sum,last_data])
        wide_data.columns = wide_data.columns.droplevel(level=0)
        
        
        
        # rename new columns & lower capitalise
        new_columns = []

        for ind, col in enumerate(wide_data.columns):
    
            if ind < wide_data.columns.shape[0]/6:
                col = 'mean_'+col            
                new_columns.append(col)

            elif ind >= wide_data.columns.shape[0]/6 and ind < 2*(wide_data.columns.shape[0]/6):
                col = 'min_'+col
                new_columns.append(col)
        
            elif ind >= 2*(wide_data.columns.shape[0]/6) and ind < 3*(wide_data.columns.shape[0]/6):
                col = 'max_'+col
                new_columns.append(col)
        
            elif ind >= 3*(wide_data.columns.shape[0]/6) and ind < 4*(wide_data.columns.shape[0]/6):
                col = 'first_'+col
                new_columns.append(col)
                
            elif ind >= 4*(wide_data.columns.shape[0]/6) and ind < 5*(wide_data.columns.shape[0]/6):
                col = 'sum_'+col
                new_columns.append(col)

            else:
                col = 'last_'+col
                new_columns.append(col)
        
        wide_data.columns = new_columns
        wide_data.columns = wide_data.columns.str.lower()
        
        
        # rename descriptor row
        wide_data.rename(columns={'mean_age':'age','mean_gender':'gender','mean_height':'height',
                                    'mean_icutype':'icutype','mean_recordid':'recordid'},inplace=True)
        
        
        # drop min/max/first/last descriptor rows
        drop_col = wide_data.columns[wide_data.columns.str.contains(
            '\w+_age|\w+_height|\w+_gender|\w+_icutype|\w+_recordid')]
        
        wide_data.drop(drop_col,axis=1,inplace=True)
        
        # set recordid as index
        wide_data.set_index(['recordid'],inplace = True)
        
        # replace -1 as NaN
        wide_data.replace(-1,np.nan,inplace=True)
        
        main = main.append(wide_data)
        
# merge main data and label data
mortality = main.merge(label,how='outer',left_index=True,right_index=True)

In [13]:
mortality.isnull().sum()

age                     0
first_albumin        2385
first_alp            2310
first_alt            2279
first_ast            2275
first_bilirubin      2282
first_bun              64
first_cholesterol    3695
first_creatinine       64
first_diasabp        1201
first_fio2           1283
first_gcs              64
first_glucose         113
first_hco3             76
first_hct              64
first_hr               63
first_k                96
first_lactate        1817
first_map            1208
first_mechvent       1471
first_mg              103
first_na               75
first_nidiasabp       517
first_nimap           519
first_nisysabp        507
first_paco2           977
first_pao2            977
first_ph              960
first_platelets        68
first_resprate       2899
first_sao2           2208
first_sysabp         1201
first_temp             64
first_troponini      3795
first_troponint      3137
first_urine           117
first_wbc              73
first_weight          326
gender                  3
height               1894
icutype                 0
last_albumin         2385
last_alp             2310
last_alt             2279
last_ast             2275
last_bilirubin       2282
last_bun               64
last_cholesterol     3695
last_creatinine        64
last_diasabp         1201
last_fio2            1283
last_gcs               64
last_glucose          113
last_hco3              76
last_hct               64
last_hr                63
last_k                 96
last_lactate         1817
last_map             1208
last_mechvent        1471
last_mg               103
last_na                75
last_nidiasabp        517
last_nimap            519
last_nisysabp         507
last_paco2            977
last_pao2             977
last_ph               960
last_platelets         68
last_resprate        2899
last_sao2            2208
last_sysabp          1201
last_temp              64
last_troponini       3795
last_troponint       3137
last_urine            117
last_wbc               73
last_weight           296
max_albumin          2385
max_alp              2310
max_alt              2279
max_ast              2275
max_bilirubin        2282
max_bun                64
max_cholesterol      3695
max_creatinine         64
max_diasabp          1201
max_fio2             1283
max_gcs                64
max_glucose           113
max_hco3               76
max_hct                64
max_hr                 63
max_k                  96
max_lactate          1817
max_map              1208
max_mechvent         1471
max_mg                103
max_na                 75
max_nidiasabp         517
                     ...
mean_lactate         1817
mean_map             1208
mean_mechvent        1471
mean_mg               103
mean_na                75
mean_nidiasabp        517
mean_nimap            519
mean_nisysabp         507
mean_paco2            977
mean_pao2             977
mean_ph               960
mean_platelets         68
mean_resprate        2899
mean_sao2            2208
mean_sysabp          1201
mean_temp              64
mean_troponini       3795
mean_troponint       3137
mean_urine            117
mean_wbc               73
mean_weight           296
min_albumin          2385
min_alp              2310
min_alt              2279
min_ast              2275
min_bilirubin        2282
min_bun                64
min_cholesterol      3695
min_creatinine         64
min_diasabp          1201
min_fio2             1283
min_gcs                64
min_glucose           113
min_hco3               76
min_hct                64
min_hr                 63
min_k                  96
min_lactate          1817
min_map              1208
min_mechvent         1471
min_mg                103
min_na                 75
min_nidiasabp         517
min_nimap             519
min_nisysabp          507
min_paco2             977
min_pao2              977
min_ph                960
min_platelets          68
min_resprate         2899
min_sao2             2208
min_sysabp           1201
min_temp               64
min_troponini        3795
min_troponint        3137
min_urine             117
min_wbc                73
min_weight            326
sum_albumin          2385
sum_alp              2310
sum_alt              2279
sum_ast              2275
sum_bilirubin        2282
sum_bun                64
sum_cholesterol      3695
sum_creatinine         64
sum_diasabp          1201
sum_fio2             1283
sum_gcs                64
sum_glucose           113
sum_hco3               76
sum_hct                64
sum_hr                 63
sum_k                  96
sum_lactate          1817
sum_map              1208
sum_mechvent         1471
sum_mg                103
sum_na                 75
sum_nidiasabp         517
sum_nimap             519
sum_nisysabp          507
sum_paco2             977
sum_pao2              977
sum_ph                960
sum_platelets          68
sum_resprate         2899
sum_sao2             2208
sum_sysabp           1201
sum_temp               64
sum_troponini        3795
sum_troponint        3137
sum_urine             117
sum_wbc                73
sum_weight            296
saps-i                  0
sofa                    0
length_of_stay          0
survival                0
in-hospital_death       0
Length: 231, dtype: int64

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

Obtain total Urine Output (48 hours)
</div>

In [17]:
drop_col = ['max_urine','min_urine','first_urine','last_urine','mean_urine']
mortality.drop(drop_col,axis=1,inplace=True)

In [21]:
drop_sum = []
for col in mortality.columns[mortality.columns.str.contains('sum_\w+')]:
    if col != 'sum_urine':
        drop_sum.append(col)

In [23]:
mortality.drop(drop_sum,axis=1,inplace=True)

In [24]:
mortality.to_pickle('mortality_UO.pickle')

In [25]:
mortality.head()

,age,first_albumin,first_alp,first_alt,first_ast,first_bilirubin,first_bun,first_cholesterol,first_creatinine,first_diasabp,first_fio2,first_gcs,first_glucose,first_hco3,first_hct,first_hr,first_k,first_lactate,first_map,first_mechvent,first_mg,first_na,first_nidiasabp,first_nimap,first_nisysabp,first_paco2,first_pao2,first_ph,first_platelets,first_resprate,first_sao2,first_sysabp,first_temp,first_troponini,first_troponint,first_wbc,first_weight,gender,height,icutype,last_albumin,last_alp,last_alt,last_ast,last_bilirubin,last_bun,last_cholesterol,last_creatinine,last_diasabp,last_fio2,last_gcs,last_glucose,last_hco3,last_hct,last_hr,last_k,last_lactate,last_map,last_mechvent,last_mg,last_na,last_nidiasabp,last_nimap,last_nisysabp,last_paco2,last_pao2,last_ph,last_platelets,last_resprate,last_sao2,last_sysabp,last_temp,last_troponini,last_troponint,last_wbc,last_weight,max_albumin,max_alp,max_alt,max_ast,max_bilirubin,max_bun,max_cholesterol,max_creatinine,max_diasabp,max_fio2,max_gcs,max_glucose,max_hco3,max_hct,max_hr,max_k,max_lactate,max_map,max_mechvent,max_mg,max_na,max_nidiasabp,max_nimap,max_nisysabp,max_paco2,max_pao2,max_ph,max_platelets,max_resprate,max_sao2,max_sysabp,max_temp,max_troponini,max_troponint,max_wbc,max_weight,mean_albumin,mean_alp,mean_alt,mean_ast,mean_bilirubin,mean_bun,mean_cholesterol,mean_creatinine,mean_diasabp,mean_fio2,mean_gcs,mean_glucose,mean_hco3,mean_hct,mean_hr,mean_k,mean_lactate,mean_map,mean_mechvent,mean_mg,mean_na,mean_nidiasabp,mean_nimap,mean_nisysabp,mean_paco2,mean_pao2,mean_ph,mean_platelets,mean_resprate,mean_sao2,mean_sysabp,mean_temp,mean_troponini,mean_troponint,mean_wbc,mean_weight,min_albumin,min_alp,min_alt,min_ast,min_bilirubin,min_bun,min_cholesterol,min_creatinine,min_diasabp,min_fio2,min_gcs,min_glucose,min_hco3,min_hct,min_hr,min_k,min_lactate,min_map,min_mechvent,min_mg,min_na,min_nidiasabp,min_nimap,min_nisysabp,min_paco2,min_pao2,min_ph,min_platelets,min_resprate,min_sao2,min_sysabp,min_temp,min_troponini,min_troponint,min_wbc,min_weight,sum_urine,saps-i,sofa,length_of_stay,survival,in-hospital_death
recordid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
132539.0,54.0,NaN,NaN,NaN,NaN,NaN,13.0,NaN,0.8,NaN,NaN,15.0,205.0,26.0,33.7,73.0,4.4,NaN,NaN,NaN,1.5,137.0,65.0,92.33,147.0,NaN,NaN,NaN,221.0,19.0,NaN,NaN,35.1,NaN,NaN,11.2,NaN,0.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,8.0,NaN,0.7,NaN,NaN,15.0,115.0,28.0,30.3,86.0,4.0,NaN,NaN,NaN,1.9,136.0,55.0,79.33,128.0,NaN,NaN,NaN,185.0,23.0,NaN,NaN,37.8,NaN,NaN,9.4,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,0.8,NaN,NaN,15.0,205.0,28.0,33.7,86.0,4.4,NaN,NaN,NaN,1.9,137.0,67.0,92.33,157.0,NaN,NaN,NaN,221.0,24.0,NaN,NaN,38.2,NaN,NaN,11.2,NaN,NaN,NaN,NaN,NaN,NaN,10.500000,NaN,0.750000,NaN,NaN,14.923077,160.000000,27.000000,32.500000,70.810811,4.20,NaN,NaN,NaN,1.700000,136.500000,50.147059,71.559118,114.382353,NaN,NaN,NaN,203.000000,17.428571,NaN,NaN,37.357143,NaN,NaN,10.300000,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,0.7,NaN,NaN,14.0,115.0,26.0,30.3,58.0,4.0,NaN,NaN,NaN,1.5,136.0,39.0,58.67,96.0,NaN,NaN,NaN,185.0,12.0,NaN,NaN,35.1,NaN,NaN,9.4,NaN,6500.0,6.0,1.0,5.0,-1.0,0.0
132540.0,76.0,NaN,NaN,NaN,NaN,NaN,16.0,NaN,0.8,67.0,1.0,3.0,105.0,21.0,24.7,88.0,4.3,NaN,79.0,1.0,3.1,139.0,38.0,49.33,72.0,34.0,344.0,7.45,164.0,NaN,99.0,105.0,35.2,NaN,NaN,7.4,76.0,1.0,175.3,2.0,NaN,NaN,NaN,NaN,NaN,21.0,NaN,1.3,51.0,0.4,15.0,146.0,24.0,29.4,65.0,3.5,NaN,69.0,1.0,1.9,135.0,49.0,68.33,107.0,46.0,140.0,7.37,135.0,NaN,97.0,103.0,37.1,NaN,NaN,13.3,81.6,NaN,NaN,NaN,NaN,NaN,21.0,NaN,1.3,81.0,1.0,15.0,146.0,24.0,30.7,90.0,4.3,NaN,100.0,1.0,3.1,139.0,67.0,88.33,131.0,46.0,445.0,7.45,226.0,NaN,99.0,138.0,37.9,NaN,NaN,13.3,81.6,NaN,NaN,NaN,NaN,NaN,18.333333,NaN,1.100000,58.897059,0.56,13.333333,125.500000,22.333333,28.655556,80.794118,3.90,NaN,76.940299,1.0,2.300000,137.000000,56.714286,75.308571,112.500000,38.857143,210.142857,7.395,178.600000,NaN,96.833333,113.411765,36.939130,NaN,NaN,11.266667,80.670588,NaN,NaN,NaN,NaN,NaN,16.0,NaN,0.8,32.0,0.4,3.0,105.0,21.0,24.7,65.0,3.5,NaN,43.0,1.0,1.9,135.0,38.0,49.33,72.0,33.0,82.0,7.34,135.0,NaN,93.0,66.0,34.5,NaN,NaN,7.4,76.0,6214.0,16.0,8.0,8.0,-1.0,0.0
132541.0,44.0,2.7,127.0,91.0,235.0,3.0,8.0,NaN,0.4,81.0,1.0,7.0,141.0,24.0,28.5,100.0,3.3,1.3,107.0,1.0,1.9,137.0,84.0,100.30,133.0,37.0,65.0,7.51,72.0,NaN,95.0,148.0,37.8,NaN,NaN,4.2,56.7,0.0,NaN,3.0,2.3,105.0,75.0,164.0,2.8,3.0,NaN,0.3,70.0,0.4,5.0,143.0,25.0,29.4,71.0,3.7,0.9,92.0,1.0,1.7,138.0,84.0,103.00,141.0,37.0,173.0,7.47,113.0,NaN,95.0,126.0,37.2,NaN,NaN,6.2,56.7,2.7,127.0,91.0,235.0,3.0,8.0,NaN,0.4,81.0,1.0,8.0,143.0,26.0,29.4,113.0,8.6,1.9,107.0,1.0,1.9,140.0,95.0,110.00,150.0,37.0,232.0,7.51,113.0,NaN,95.0,148.0,39.0,NaN,NaN,6.2,56.7,2.5,116.0,83.0,199.5,2.9,4.666667,NaN,0.333333,67.125000,0.50,5.923077,134.333333,25.000000,28.460000,83.759259,4.26,1.366667,90.437500,1.0,1.720000,138.333333,79.000000,96.751316,132.263158,35.500000,134.500000,7.495,89.666667,NaN,95.000000,125.687500,37.800000,NaN,NaN,4.700000,56.700000,2.3,105.0,75.0,164.0,2.8,3.0,NaN,0.3,52.0,0.4,5.0,119.0,24.0,26.7,57.0,2.3,0.9,72.0,1.0,1.3,137.0,66.0,83.33,111.0,33.0,65.0,7.47,72.0,NaN,95.0,103.0,36.7,NaN,NaN,3.7,56.7,5123.0,21.0,11.0,19.0,-1.0,0.0
132543.0,68.0,4.4,105.0,12.0,15.0,0.2,23.0,NaN,0.9,NaN,NaN,15.0,129.0,28.0,41.3,79.0,4.0,NaN,NaN,NaN,2.1,140.0,63.0,86.67,134.0,NaN,NaN,NaN,391.0,19.0,NaN,NaN,36.3,NaN,NaN,11.5,84.6,1.0,180.3,3.0,4.4,105.0,12.0,15.0,0.2,10.0,NaN,0.7,NaN,NaN,15.0,117.0,28.0,36.3,79.0,3.8,NaN,NaN,NaN,1.9,137.0,81.0,98.67,134.0,NaN,NaN,NaN,284.0,22.0,NaN,NaN,37.0,NaN,NaN,7.9,84.6,4.4,105.0,12.0,15.0,0.2,23.0,NaN,0.9,NaN,NaN,15.0,129.0,28.0,41.3,88.0,4.2,NaN,NaN,NaN,2.1,141.0,81.0,100.70,140.0,NaN,NaN,NaN,391.0,24.0,NaN,NaN,37.0,NaN,NaN,11.5,84.6,4.4,105.0,12.0,15.0,0.2,17.666667,NaN,0.766667,NaN,NaN,14.944444,117.333333,27.666667,37.442857,70.983333,4.00,NaN,NaN,NaN,2.033333,139.333333,65.051724,83.885517,121.551724,NaN,NaN,NaN,330.000000,15.457627,NaN,NaN,36.223077,NaN,NaN,9.400000,84.600000,4.4,105.0,12.0,15.0,0.2,10.0,NaN,0.7,NaN,NaN,14.0,106.0,27.0,36.1,57.0,3.8,NaN,NaN,NaN,1.9,137.0,45.0,68.33,102.0,NaN,NaN,NaN,284.0,6.0,NaN,NaN,35.1,NaN,NaN,7.9,84.6,3275.0,7.0,1.0,9.0,575.0,0.0
132545.0,88.0,3.3,NaN,NaN,NaN,NaN,45.0,NaN,1.0,NaN,NaN,15.0,113.0,18.0,22.6,93.0,6.0,NaN,NaN,NaN,1.5,140.0,41.0,75.33,144.0,NaN,NaN,NaN,109.0,24.0,NaN,NaN,37.8,NaN,NaN,3.8,NaN,0.0,NaN,3.0,3.3,NaN,NaN,NaN,NaN,25.0,NaN,1.0,NaN,NaN,15.0,92.0,20.0,30.9,68.0,4.1,NaN,NaN,NaN,1.6,139.0,42.0,73.00,135.0,NaN,NaN,NaN,97.0,16.0,NaN,NaN,36.7,NaN,NaN,4.8,NaN,3.3,NaN,NaN,NaN,NaN,45.0,NaN,1.0,NaN,NaN,15.0,113.0,20.0,32.4,94.0,6.0,NaN,NaN,NaN,1.6,140.0,96.0,105.70,157.0,NaN,NaN,NaN,109.0,27.0,NaN,NaN,37.8,NaN,NaN,4.8,NaN,3.3,NaN,NaN,NaN,NaN,35.000000,NaN,1.000000,NaN,NaN,15.000000,102.500000,19.000000,29.550000,74.958333,4.32,NaN,NaN,NaN,1.550000,139.500000,45.720930,74.946512,133.395349,NaN,NaN,NaN,103.000000,19.166667,NaN,NaN,36.880000,NaN,NaN,4.300000,NaN,3.3,NaN,NaN,NaN,NaN,25.0,NaN,1.0,NaN,NaN,15.0,92.0,18.0,22.6,65.0,3.8,NaN,NaN,NaN,1.5,139.0,26.0,52.33,105.0,NaN,NaN,NaN,97.0,13.0,NaN,NaN,35.8,NaN,NaN,3.8,NaN,2361.0,17.0,2.0,4.0,918.0,0.0

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Data Cleaning</span></b>
<br><br>
<b>Step 1:</b> Drop all columns with more than 75% NaN values
<br><b>Step 2:</b> Drop all rows with more than 50% NaN values
<br><b>Step 3:</b> Drop all other outcomes labels except 'in-hospital_death'
</div>

In [ ]:
# NaN values count (columns)

#null_col = mortality.isnull().sum()
#null_col[null_col > 1000].index  # columns that contain more than 3/4 NaN values (75% of the rows)

#mortality.drop(null_col[null_col > 1000].index,axis=1,inplace = True)

In [ ]:
# NaN values count (rows)

#mortality['NaNs'] = mortality.isnull().sum(axis=1)
#mortality[mortality['NaNs']>57].index  # rows that contain more than 57 NaN values (50% of the features)

#mortality.drop(mortality[mortality['NaNs']>57].index,inplace=True)

In [ ]:
# Drop other labels

#label_others = mortality.drop(['saps-i','sofa','length_of_stay','survival'],axis=1)
#mortality.drop(['saps-i','sofa','length_of_stay','survival'],axis=1,inplace=True)

In [ ]:
# Drop NaN column

#mortality.drop(['NaNs'],axis=1,inplace=True)

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Imputing Missing Data</span></b>
<br><br>
<b>1:</b> Impute values based on median of gender, age & icutype
<br><b>2:</b> Impute values based on KNN
</div>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Feature Selection</span></b>
<br><br>
<b>1: </b>Variance Inflation Factor (multi-colinearity)
<br>
<b>2: </b>Near Zero Variance
<br>
<b>3: </b>Chi2 Test
<br>
<b>4: </b>PCA
</div>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Imbalance Class</span></b>
<br><br>
<b>1: </b>NearMiss2
<br>
<b>2: </b>SMOTE
<br>
<b>3: </b>SMOTEENN
<br>
<b>4: </b>EasyEnsemble
<br>
<b>5: </b>Balance Cascade
</div>

<div style="width:900px;background:#F9EECF;border:1px solid black;text-align:left;padding:20px;">

<p>

<span style="color:purple;font-size:13pt"><b>Modelling</span></b>
<br><br>
<b>1: </b>Logistic Regression
<br>
<b>2: </b>Decision Tree / Random Forest
<br>
<b>3: </b>SVM Classifier
<br>
<b>4: </b>Bagging
<br>
<b>5: </b>Boosting
</div>